export const ALLOWED_AMOUNT_OF_SELECTED_ELEMENTS = 3 as const

const LIST_VISIBLE_ITEMS = 7 as const
export const LIST_ITEM_HEIGHT = 24 as const
export const LIST_HEIGHT = LIST_ITEM_HEIGHT * LIST_VISIBLE_ITEMS